### ISSUE TITLE
PHP Fatal error: Uncaught Error: Call to a member function add_session() on null

### ISSUE THREAD

**Issue by proseLA** [lat9/upsoauth#8]
you can NOT use that `$messageStack` object on line 117 without declaring it first on line 72.  (at least that is how i would do it!)

https://github.com/lat9/upsoauth/blob/56708bfab8e55ab3b34a594952eb613c3e61823e/includes/modules/shipping/upsoauth.php#L72
https://github.com/lat9/upsoauth/blob/56708bfab8e55ab3b34a594952eb613c3e61823e/includes/modules/shipping/upsoauth.php#L117

**Comment by lat9** [comment]
Duh!

**Comment by lat9** [comment]
Thankfully (?) it was introduced in the v1.0.0 to v1.1.0 rewrite; thanks for the report.
